# Generated by Django 4.1.3 on 2022-11-14 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebateTopic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('closestatus', models.BooleanField(default=False)),
                ('aduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('view_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='USID', to='myapp.debatetopic')),
                ('user', models.ManyToManyField(to='myapp.debatetopic')),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('vote_id', models.AutoField(primary_key=True, serialize=False)),
                ('votestatus', models.BooleanField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ID', to='myapp.debatetopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='USeID', to=settings.AUTH_USER_MODEL)),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VID', to='myapp.views')),
            ],
        ),
        migrations.CreateModel(
            name='UsersType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('Mod', 'Moderator'), ('DU', 'Debater')], max_length=25)),
                ('userstatus', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TopicSuggest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsname', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepateWinner',
            fields=[
                ('dw_id', models.AutoField(primary_key=True, serialize=False)),
                ('winstatus', models.BooleanField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UID', to='myapp.debatetopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='USEID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
